### ISSUE TITLE
javascript puzzle no longer works since 2020

### ISSUE THREAD

**Issue by disaster123** [C0nw0nk/Nginx-Lua-Anti-DDoS#12]
Example:
x-auth-answer result | 21253816 should be: 24212124

so the results no longer match - this happens since new year 2020.

**Comment by disaster123** [comment]
Safari Chrome and others solve this puzzle like this:
```
20200104 + 04012020
> 21253816
```

My calculator says this is 24212124 ??

**Comment by disaster123** [comment]
ok preseeding zeros are not allowed in JS - so this can be solved to change the JS code to:
parseInt(20200104) + parseInt(04012020)

**Comment by disaster123** [comment]
Patch to fix this issue:
```
commit b3237a1ddaff1855932f07b671e3db0c18670b1a (HEAD -> master)
Author: Stefan Priebe <s.priebe@profihost.ag>
Date:   Sun Jan 5 22:38:35 2020 +0100

    JavascriptPuzzleVars stopped working since 2020 as JS calcs 20200104 + 04012020 into 21253816
    
    To fix number calculation with leading zeros:
    * use parseInt
    * explicit pass of a string
    * define base of 10

diff --git a/lua/anti_ddos_challenge.lua b/lua/anti_ddos_challenge.lua
index 73562bd..5fc20b8 100644
--- a/lua/anti_ddos_challenge.lua
+++ b/lua/anti_ddos_challenge.lua
@@ -137,7 +137,7 @@ Javascript Puzzle for web browser to solve do not touch this unless you understa
 
 --Make our Javascript puzzle a little bit more dynamic than the static equation above it will change every 24 hours :) I made this because the static one is pretty poor security compared to this but this can be improved allot though.
 --TODO: IMPROVE THIS!
-local JavascriptPuzzleVars = [[]] .. os.date("%Y%m%d",os.time()-24*60*60) .. [[ + ]] .. os.date("%d%m%Y",os.time()-24*60*60) ..[[]] --Javascript output of our two random numbers
+local JavascriptPuzzleVars = [[parseInt("]] .. os.date("%Y%m%d",os.time()-24*60*60) .. [[", 10) + parseInt("]] .. os.date("%d%m%Y",os.time()-24*60*60) ..[[", 10)]] --Javascript output of our two random numbers
 local JavascriptPuzzleVars_answer = os.date("%Y%m%d",os.time()-24*60*60) + os.date("%d%m%Y",os.time()-24*60*60) --lua output of our two random numbers
 local JavascriptPuzzleVars_answer = math.floor(JavascriptPuzzleVars_answer+0.5) --fix bug removing the 0. decimal on the end of the figure
 local JavascriptPuzzleVars_answer = tostring(JavascriptPuzzleVars_answer) --convert the numeric output to a string
```

**Comment by Webuser6666** [comment]
> Patch to fix this issue:
> 
> commit b3237a1ddaff1855932f07b671e3db0c18670b1a (HEAD -> master)
> Author: Stefan Priebe <s.priebe@profihost.ag>
> Date:   Sun Jan 5 22:38:35 2020 +0100
> 
>     JavascriptPuzzleVars stopped working since 2020 as JS calcs 20200104 + 04012020 into 21253816
>     
>     To fix number calculation with leading zeros:
>     * use parseInt
>     * explicit pass of a string
>     * define base of 10
> 
> diff --git a/lua/anti_ddos_challenge.lua b/lua/anti_ddos_challenge.lua
> index 73562bd..5fc20b8 100644
> --- a/lua/anti_ddos_challenge.lua
> +++ b/lua/anti_ddos_challenge.lua
> @@ -137,7 +137,7 @@ Javascript Puzzle for web browser to solve do not touch this unless you understa
>  
>  --Make our Javascript puzzle a little bit more dynamic than the static equation above it will change every 24 hours :) I made this because the static one is pretty poor security compared to this but this can be improved allot though.
>  --TODO: IMPROVE THIS!
> -local JavascriptPuzzleVars = [[]] .. os.date("%Y%m%d",os.time()-24*60*60) .. [[ + ]] .. os.date("%d%m%Y",os.time()-24*60*60) ..[[]] --Javascript output of our two random numbers
> +local JavascriptPuzzleVars = [[parseInt("]] .. os.date("%Y%m%d",os.time()-24*60*60) .. [[", 10) + parseInt("]] .. os.date("%d%m%Y",os.time()-24*60*60) ..[[", 10)]] --Javascript output of our two random numbers
>  local JavascriptPuzzleVars_answer = os.date("%Y%m%d",os.time()-24*60*60) + os.date("%d%m%Y",os.time()-24*60*60) --lua output of our two random numbers
>  local JavascriptPuzzleVars_answer = math.floor(JavascriptPuzzleVars_answer+0.5) --fix bug removing the 0. decimal on the end of the figure
>  local JavascriptPuzzleVars_answer = tostring(JavascriptPuzzleVars_answer) --convert the numeric output to a string

and why put one cookie current is normal?

**Comment by disaster123** [comment]
Pull request is here https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/pull/13

**Comment by disaster123** [comment]
thx for merging

**Comment by Webuser6666** [comment]
> thx for merging

thanks
