### ISSUE TITLE
problem with install module

### ISSUE THREAD

**Issue by Anti067** [C0nw0nk/Nginx-Lua-Anti-DDoS#17]
hello, im use nginx 1.17.8 with ubuntu xenial and after put the script i take a error...

nginx: [emerg] unknown directive "access_by_lua_file" in /etc/nginx/conf.d/default.conf:11

how can i fix?

**Comment by C0nw0nk** [comment]
Does your Nginx have this addon built into / compiled with it.

https://github.com/openresty/lua-nginx-module

That is the only reason your error would say `unknown directive "access_by_lua_file"` Because your not running Lua.
