### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Webuser6666** [C0nw0nk/Nginx-Lua-Anti-DDoS#18]
How to add a subnet?

local ip_whitelist = {
--"127.0.0.1", --localhost
--"192.168.0.1", --localhost
}

**Comment by C0nw0nk** [comment]
I would need to write a function in first before you can use subnet masks currently it only supports IP adresses

**Comment by kxknet** [comment]
> 
> 
> I would need to write a function in first before you can use subnet masks currently it only supports IP adresses

How to send you letter?I no use facebook, please write me telegram @kxkwork

**Comment by kxknet** [comment]
Please read email

**Comment by C0nw0nk** [comment]
Done.

https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/9fb67fef2b394b5f76bb50ed321c04102fbee15b
