### ISSUE TITLE
Add blacklist ip

### ISSUE THREAD

**Issue by kxknet** [C0nw0nk/Nginx-Lua-Anti-DDoS#19]
How add bots to blacklist.conf nginx

**Comment by C0nw0nk** [comment]
When you say bots what do you mean a list of user-agents to block access to ?

I did give the ability to blacklist IP addresses https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/blob/master/lua/anti_ddos_challenge.lua#L196

**Comment by kxknet** [comment]
See mail please
