### ISSUE TITLE
Add useragent whitelist

### ISSUE THREAD

**Issue by kxknet** [C0nw0nk/Nginx-Lua-Anti-DDoS#20]
Please add user agent whitelist

**Comment by C0nw0nk** [comment]
I already have just been building and ipv4 and ipv6 subnet function so i can push it as a update.

**Comment by C0nw0nk** [comment]
Done.
https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/9fb67fef2b394b5f76bb50ed321c04102fbee15b
