### ISSUE TITLE
local expire_time bug

### ISSUE THREAD

**Issue by rx-209** [C0nw0nk/Nginx-Lua-Anti-DDoS#23]
Greetings.
Using script with tor browser 9.0.5 (based on Mozilla Firefox 68.5.0esr) (64-bit) and onion address.

local remote_addr = "tor"  as settings

If i set any numbers for "local expire_time" less than 86400 (86399 and less) -  auth page doesnt change to website.

**Comment by C0nw0nk** [comment]
I am unable to replicate this, Will leave it open to see if others have this problem or not be good to find out if it is unique to you or not.

**Comment by rx-209** [comment]
Found problem - removed line 1858 and got that issue.
