### ISSUE TITLE
[feature suggestion] add logo to page

### ISSUE THREAD

**Issue by x0rzkov** [C0nw0nk/Nginx-Lua-Anti-DDoS#24]
Hi,

Hope you are doing well !

Is it possible to add a logo to the waiting page ? It would nice to customise this page.

Cheers,
X

**Comment by gayanov** [comment]
you can add custom animation, created your or search in codepen.io, edit html tag, and save sytacks in antiddow lua file

**Comment by C0nw0nk** [comment]
You could convert your image to base64 and insert its `img` html tags with the base64 string into the HTML output template at the end of the script.

**Comment by x0rzkov** [comment]
while give a try to the base64 trick. Thanks guys
