### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by wafedsf5** [C0nw0nk/Nginx-Lua-Anti-DDoS#27]
Sorry to ask here, but I need to talk with you!
May I have any contact?

**Comment by C0nw0nk** [comment]
Facebook ?

**Comment by C0nw0nk** [comment]
@wafedsf5 what is the dilema that you are having ?

**Comment by wafedsf5** [comment]
Email / Skype / Discord, any of them?

**Comment by C0nw0nk** [comment]
That is all i use don't bother with the others right now.
