### ISSUE TITLE
Nginx logging

### ISSUE THREAD

**Issue by rx-209** [C0nw0nk/Nginx-Lua-Anti-DDoS#28]
Hi. How to disable nginx logging for authorise page? I wanted to log requests after authorisation only. 
Or how to split general nginx loging into 2 files: auth page and authorised requests?

**Comment by C0nw0nk** [comment]
what is your logging code at the moment ? Your logging url user-agent ?

**Comment by rx-209** [comment]
log_format  cache $remote_addr - $remote_user [$time_local] $request "$status" $body_bytes_sent "$http_referer" "$host" "$http_user_agent" "$http_x_forwarded_for" "$upstream_cache_status" "$upstream_addr" "$upstream_response_time" "$request_time";

Actually, i guess log format could be any.  For example, part from website nginx config:

server { 
.....
access_by_lua_file /etc/nginx/lua/anti_ddos_challenge.lua;
access_log /var/log/nginx/access.log
......
}

All requests to auth page from ddos bots are collected in front.access.log. I wanted exclude ddos logging (requests before lua firewall) or use another log file for that.

**Comment by C0nw0nk** [comment]
You could add `ngx.log("Log details " .. remote_addr)` to my code. If that would help you.

It could go so you log before auth and those who have been verified and granted access
