### ISSUE TITLE
Whitelist search engines

### ISSUE THREAD

**Issue by TechFocus** [C0nw0nk/Nginx-Lua-Anti-DDoS#3]
Is it possible to whitelist search engines IP ranges to bypass the authentication?

**Comment by C0nw0nk** [comment]
Yeah I will add it as a feature :)

**Comment by TechFocus** [comment]
Any ETA on implementing whitelist?

**Comment by C0nw0nk** [comment]
https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/499bc58631dfa967edbd48a62c8bbc3a15fddcfd

Done.

**Comment by TechFocus** [comment]
Thank you for the update.

It's possible to add IP addresses in a separate file and make the script read them from this file?
