### ISSUE TITLE
Add new obfuscator

### ISSUE THREAD

**Issue by gayanov** [C0nw0nk/Nginx-Lua-Anti-DDoS#31]
Can you add new obfuscator [obfuscator.io](https://obfuscator.io) js code?

**Comment by C0nw0nk** [comment]
It is possible but I would have to look at the way they obfuscate their code learn it and then write it completely in Lua and add it to my obfuscation function.

It is possible and if people want to take existing obfuscation methods and write them in Lua to add to this please do but currently I do not have the time to be able to do that with the other features i am trying to finish building and push out.

But here is a list of obfuscation methods I did want to build into my script at some point. It is just finding the time to rewrite them completely in Lua.

I have ordered this list in the order that I wanted to build them as priority.

JSFuck http://www.jsfuck.com/ (This is one of the most interesting Javascript things i have seen)

AAEncoder https://github.com/mervick/php-aaencoder (I love the way you can obfuscate strings into unicode character chars to be executed by javascript with funny anime faces)

Javascript Packer Dean Edwards http://dean.edwards.name/unpacker/ (This is the most common and famous i have seen publicly but it is also written in PHP not Lua so i would have to rewrite it in Lua time consuming)
