### ISSUE TITLE
User Agent Whitelist Does not Work

### ISSUE THREAD

**Issue by Sylvvvia** [C0nw0nk/Nginx-Lua-Anti-DDoS#32]
### Issue title
User Agent whitelist is not working
### Issue Description
i've done whitelist for google but it is not working at all, google bot still receives 503 error. table code below:

local user_agent_whitelist_var = ngx.var.http_user_agent
local user_agent_whitelist_table = {
	{
		"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
		2,
	},
	{
		"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
		1,
	},
	{
		"Googlebot/2.1 (+http://www.google.com/bot.html)",
		1,
	},
	{
		"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Safari/537.36 Chrome-Lighthouse",
		1,
	},
	{
		"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse",
		1,
	},
	{
		"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Mobile Safari/537.36",
		1,
	},
	{
		"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36",
		1,
	},
	{
		"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z‡ Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
		1,
	},
	{
		"Mozilla/5.0 (compatible; Bingbot/2.0; +http://www.bing.com/bingbot.htm)",
		1,
	},
	{
		"APIs-Google (+https://developers.google.com/webmasters/APIs-Google.html)",
		1,
	},
}

### Versions:

- Browser(s):
- Nginx version: Latest OpenResty
- Operating system of web server running Nginx: Centos7

### Nginx config:
```
paste your nginx config here
```

### Screenshot(s):

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Settings:

Haven't changed anything.

**Comment by C0nw0nk** [comment]
```
local user_agent_whitelist_table = {
{
	[[Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)]],
	2,
},
{
	[[Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html)]],
	1,
},
{
	[[Googlebot/2.1 (+http://www.google.com/bot.html)]],
	1,
},
{
	[[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Safari/537.36 Chrome-Lighthouse]],
	1,
},
{
	[[Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse]],
	1,
},
{
	[[Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Mobile Safari/537.36]],
	1,
},
{
	[[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36]],
	1,
},
{
	[[Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z‡ Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)]],
	1,
},
{
	[[Mozilla/5.0 (compatible; Bingbot/2.0; +http://www.bing.com/bingbot.htm)]],
	1,
},
{
	[[APIs-Google (+https://developers.google.com/webmasters/APIs-Google.html)]],
	1,
},
}
```

You have not provided a error.log of what the error in your Nginx console is outputting that would really help but you can try the above code but without seeing the Line number or what your error logs are saying i can't help solve it without seeing that.

**Comment by Sylvvvia** [comment]
There is no error log only access log with 503 error. I'll try above one.

**Comment by C0nw0nk** [comment]
Not sure what the issue it i can't replicate it ?

**Comment by Sylvvvia** [comment]
Get current openresty. Simply half of features are not working. Useragent blacklisting seems to be working however ip whitelist is not working same as user agent whitelist. If those features are working at your server provide me with your script configuration + nginx configuration i'll try it on my server.

**Comment by C0nw0nk** [comment]
Ok so because the way the whitelist works atleast for your whitelist you could try wrapping your strings of what you are matching since they are Regex patterns in starting and ending regex tags.

`^` and `$`

So it would look like this.
```
local user_agent_whitelist_table = {
{
"^Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)$",
2,
},
}
```

My thinking is that because your strings contain things like slashes, fullstops, semi colons, braces etc it is treating them as regex when you want to escape them first. So an easy to test to proove that the user-agent whitelist works.

```
local user_agent_whitelist_table = {
{
".*", --match any user-agent
2,
},
}
```

That example would whitelist every single user-agent accessing your server and there for nobody should see the Authentication page / Javascript puzzle.

**Comment by C0nw0nk** [comment]
You just need to escape your Regex string properly. escape slashes etc the things that need to be escaped in your string so it will match.

**Comment by Sylvvvia** [comment]
I'll test it and let you know within 1 hour.

**Comment by C0nw0nk** [comment]
So on a programming basis.

I will show you.

Paste my code example into the Lua demo site https://www.lua.org/cgi-bin/demo
```
local regex = "^Mozilla/5.0 .*$" --this will work
-- this will not work
--[[
local regex = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
]]

local string = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

if string.match(string, regex) then
print("Your regex pattern works!")
end
```

**Comment by C0nw0nk** [comment]
@Sylvvvia Hopefully my example there allows you to get your regex right through testing and also shows you how it works and also shows you why it is currently not working for you :)

**Comment by C0nw0nk** [comment]
@Sylvvvia Updated my above comment(s) to show you the Regex working and escaped special chars.

Thinks like full stops slashes etc need escaping in Lua you escape them with a percentage symbol `%`

**Comment by Sylvvvia** [comment]
Can confirm it works.
