### ISSUE TITLE
Getting 404 after loading LUA in Openresty

### ISSUE THREAD

**Issue by Triniayo** [C0nw0nk/Nginx-Lua-Anti-DDoS#33]
Hey there,

I'm getting a 404 error after loading LUA in Openresty.

I've put this in my http block in nginx.conf:

```access_by_lua_file /home/anti_ddos_challenge.lua;```

I've setup Openresty like this: https://www.digitalocean.com/community/tutorials/how-to-use-the-openresty-web-framework-for-nginx-on-ubuntu-16-04

**Comment by C0nw0nk** [comment]
Do you have any error logs ? A 404 error seems highly strange since that
means not found if it was a 500 error that would be with my script but
since it is a 404 it seems to be your setup..
