### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by TcpSec** [C0nw0nk/Nginx-Lua-Anti-DDoS#35]
### Issue Description
after adding the LUA line to the server config the 404 occurred, as soon as i remove this line it will load the index.html as usual, is there a setting i missed?
### Versions:

- Browser(s):
- Nginx version: openresty
- Operating system of web server running Nginx:ubuntu

### Nginx config:
http {
    include       mime.types;
    default_type  application/octet-stream;
    lua_shared_dict antiddos 10m; #Anti-DDoS shared memory zone

   #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  ***;
         #charset koi8-r;
        access_by_lua_file conf/lua/anti_ddos_challenge.lua;
      #  access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page  404              /50x.html;

### Screenshot(s):

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Settings:

- [List here all the changes you made to the default settings]

**Comment by Sylvvvia** [comment]
Hello Your Issue is Inside location block. You're missing path to html folder.

root   html; - wrong
root /path/to/html; - correct

**Comment by TcpSec** [comment]
@Sylvvvia I've had a look at the .lua file where do I set the correct location? had a look but wasn't able to find it!
Your help is much appreciated :)

**Comment by Sylvvvia** [comment]
The most simplest way to do it is just by placing anti_ddos_challenge.lua inside home directory then set in nginx:

access_by_lua_file /home/anti_ddos_challenge.lua;

**Comment by C0nw0nk** [comment]
In your Nginx folder what is actually inside your "html" folder you should have a "conf" folder and a "logs" folder but it seems your "html" folder might be empty hence the 404 error.
