### ISSUE TITLE
Disable JavaSript

### ISSUE THREAD

**Issue by Leon-68** [C0nw0nk/Nginx-Lua-Anti-DDoS#36]
Hey,
is it possible to disable JavaSript?
If yes how? 

Thanks for your answer in advance!

**Comment by C0nw0nk** [comment]
No, it currently is not. But I could do it and make it a feature but for security of your site when under attack it really is not recommended and would not help you stay protected and online ?

**Comment by Leon-68** [comment]
> 
> 
> No, it currently is not. But I could do it and make it a feature but for security of your site when under attack it really is not recommended and would not help you stay protected and online ?

As a feature it would actually be very interesting
