### ISSUE TITLE
How to know...

### ISSUE THREAD

**Issue by Takumi86ES** [C0nw0nk/Nginx-Lua-Anti-DDoS#39]
I would like to know how I know it is working.

**Comment by C0nw0nk** [comment]
```
http {
#nginx config settings etc
access_by_lua_file anti_ddos_challenge.lua;
#more config settings and some server stuff
}
```

If you have put it into your nginx config then you should see the Anti-DDoS Javascript puzzle. Unless you changed any settings / configurations in the script. (But Script as default will show the page instantly)
