### ISSUE TITLE
The protection can be bypassed if the visitor refreshes the page

### ISSUE THREAD

**Issue by TechFocus** [C0nw0nk/Nginx-Lua-Anti-DDoS#4]
As the title says.

**Comment by para-dise** [comment]
I understand @TechFocus's concern - if a user refreshes the page before the 5 seconds are up, the 5 second cooldown will no longer appear.

Is there any possible way to have the cooldown page until the 5s are over? The current way looks unprofessional.

**Comment by para-dise** [comment]
update: using post verification instead of get seems to fix the issue.

**Comment by C0nw0nk** [comment]
Make a pull request and i will push it to the main repo to fix the problem.
