### ISSUE TITLE
Is there a way to decide in own lua code when to show Js puzzle?

### ISSUE THREAD

**Issue by disaster123** [C0nw0nk/Nginx-Lua-Anti-DDoS#40]
Hi,

I already have a bunch of lua code running and want to show the puzzle dynamically only for specific ips from my lua code.

Is this possible?

Greets,
Stefan

**Comment by Sylvvvia** [comment]
As far as i know currently it is possible to show it on specific pages however soon there should be implemented automatic attack detection system..
