### ISSUE TITLE
Downloaded .html file

### ISSUE THREAD

**Issue by 4t8k9x1k** [C0nw0nk/Nginx-Lua-Anti-DDoS#41]
### Versions:

- Browser(s):
- Nginx version: nginx/1.10.3
- Operating system of web server running Nginx: Debian 9 (Stretch)

### Nginx config:
```
server {

       access_by_lua_file conf/lua/anti_ddos_challenge.lua;

	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass PHP scripts to FastCGI server
	#
	#location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
	#	# With php-fpm (or other unix sockets):
	#	fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#	listen 80;
#	listen [::]:80;
#
#	server_name example.com;
#
#	root /var/www/example.com;
#	index index.html;
#
#	location / {
#		try_files $uri $uri/ =404;
#	}
#}
```

### Screenshot(s):

https://prnt.sc/secq29 (Screenshot)

https://prnt.sc/secqe4 (Screenshot 2)

### Settings:

- [List here all the changes you made to the default settings]

---

### Other optional information you want to add other than the above:
---

Hi,

I have set up a nginx webserver and when I open the page with layer 7 mitigation, it downloads the index.html file, although I do not want this, but want to display it. If I take out layer 7 mitigation, it works without problems, what do I have to do?

PS: Sorry for my worst English, I come from Germany.

**Comment by 4t8k9x1k** [comment]
If you need more information, write me.

**Comment by Sylvvvia** [comment]
Provide us with access log and error log of nginx.

**Comment by ali391286** [comment]
Gd

**Comment by adsanz** [comment]
I have this issue as well, it seems that is cause when the script makes a POST request back to the server at  "/" however, in my case I have both a react front-end and a django back-end,  the back-end does not suffer from that problem

It may be an issue with try_files.

I tryied setting up this:

````
--[[
The type of javascript based pingback authentication method to use if it should be GET or POST or can switch between both making it as dynamic as possible.1 = GET
2 = POST
3 = DYNAMIC
]]
local javascript_REQUEST_TYPE = 1 --Default 2

````

I thought it would change the way it works but it does not, it keeps making a POST then GET request. And it keeps downloading the file

**Comment by 4t8k9x1k** [comment]
> ### Issue Description
> ### Versions:
> * Browser(s):
> * Nginx version: nginx/1.10.3
> * Operating system of web server running Nginx: Debian 9 (Stretch)
> 
> ### Nginx config:
> ```
> server {
> 
>        access_by_lua_file conf/lua/anti_ddos_challenge.lua;
> 
> 	listen 80 default_server;
> 	listen [::]:80 default_server;
> 
> 	# SSL configuration
> 	#
> 	# listen 443 ssl default_server;
> 	# listen [::]:443 ssl default_server;
> 	#
> 	# Note: You should disable gzip for SSL traffic.
> 	# See: https://bugs.debian.org/773332
> 	#
> 	# Read up on ssl_ciphers to ensure a secure configuration.
> 	# See: https://bugs.debian.org/765782
> 	#
> 	# Self signed certs generated by the ssl-cert package
> 	# Don't use them in a production server!
> 	#
> 	# include snippets/snakeoil.conf;
> 
> 	root /var/www/html;
> 
> 	# Add index.php to the list if you are using PHP
> 	index index.html index.htm index.nginx-debian.html;
> 
> 	server_name _;
> 
> 	location / {
> 		# First attempt to serve request as file, then
> 		# as directory, then fall back to displaying a 404.
> 		try_files $uri $uri/ =404;
> 	}
> 
> 	# pass PHP scripts to FastCGI server
> 	#
> 	#location ~ \.php$ {
> 	#	include snippets/fastcgi-php.conf;
> 	#
> 	#	# With php-fpm (or other unix sockets):
> 	#	fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
> 	#	# With php-cgi (or other tcp sockets):
> 	#	fastcgi_pass 127.0.0.1:9000;
> 	#}
> 
> 	# deny access to .htaccess files, if Apache's document root
> 	# concurs with nginx's one
> 	#
> 	#location ~ /\.ht {
> 	#	deny all;
> 	#}
> }
> 
> 
> # Virtual Host configuration for example.com
> #
> # You can move that to a different file under sites-available/ and symlink that
> # to sites-enabled/ to enable it.
> #
> #server {
> #	listen 80;
> #	listen [::]:80;
> #
> #	server_name example.com;
> #
> #	root /var/www/example.com;
> #	index index.html;
> #
> #	location / {
> #		try_files $uri $uri/ =404;
> #	}
> #}
> ```
> 
> ### Screenshot(s):
> https://prnt.sc/secq29 (Screenshot)
> 
> https://prnt.sc/secqe4 (Screenshot 2)
> 
> ### Settings:
> * [List here all the changes you made to the default settings]
> 
> ### Other optional information you want to add other than the above:
> Hi,
> 
> I have set up a nginx webserver and when I open the page with layer 7 mitigation, it downloads the index.html file, although I do not want this, but want to display it. If I take out layer 7 mitigation, it works without problems, what do I have to do?
> 
> PS: Sorry for my worst English, I come from Germany.
