### ISSUE TITLE
I can bypass the protection when JavaScript turned off

### ISSUE THREAD

**Issue by TechFocus** [C0nw0nk/Nginx-Lua-Anti-DDoS#5]
I tried both Chrome and Firefox.

**Comment by C0nw0nk** [comment]
Impossible you don't seem to understand your browser can't send XHR requests without Javascript being enabled please clear all your browsers cookies and check your Nginx configuration to make sure the location on your server the script is running.

**Comment by C0nw0nk** [comment]
Also please stop opening a new issue for something you posted previously. Post your replies here.

**Comment by TechFocus** [comment]
My bad, it requires to restart Nginx after disabling browser JavaScript.

> Also please stop opening a new issue for something you posted previously. Post your replies here.

What I posted previously #4 is different than this issue, it's for bypassing the protection before completing 5 seconds by reloading the page. I thought it will be similar to Cloudflare which blocks access without completing 5 seconds.

**Comment by C0nw0nk** [comment]
> My bad, it requires to restart Nginx after disabling browser JavaScript.
> 
> > Also please stop opening a new issue for something you posted previously. Post your replies here.
> 
> What I posted previously #4 is different than this issue, it's for bypassing the protection before completing 5 seconds by reloading the page. I thought it will be similar to Cloudflare which blocks access without completing 5 seconds.

I actually built in a feature to do just that I will try finish it tonight I push my updated code to the main repo for you.

**Comment by TechFocus** [comment]
Is there any news about adding this feature?
