### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by B0pol** [C0nw0nk/Nginx-Lua-Anti-DDoS#56]
What is this project's licence?

**Comment by TheFrenchGhosty** [comment]
It's copyrighted, with source available: https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/blob/master/lua/anti_ddos_challenge.lua#L3

**Comment by basisbit** [comment]
please add a LICENSE file to the repository, so that people clearly see that this is not free/libre open source software.
Just hiding the license in the lua file will cause many people to miss that or only see it after already spending some time on it. Thanks.
