### ISSUE TITLE
Error 500 after checking browser

### ISSUE THREAD

**Issue by gayanov** [C0nw0nk/Nginx-Lua-Anti-DDoS#6]
Hello, I installed your module, translated and configured (changed the key), as a result, after the redirect, it displays a 500 error

Screenhoots:
[https://i.imgur.com/NhIRqEP.png](url)

Applications version:
nginx: 1.14.2
lua: 2.0.5

**Comment by C0nw0nk** [comment]
So what happens when you put the script in and do not touch or modify anything ? (Completely default)

**Comment by C0nw0nk** [comment]
Also what browser etc are you using.

**Comment by gayanov** [comment]
antiddos.rocketdonate.ru

**Comment by C0nw0nk** [comment]
@gayanov can you provide what changes you made to the script and / or your nginx config.

**Comment by gayanov** [comment]
anti_ddos_challenge.lua
https://pastebin.com/raw/vwQFZ2GE

I am changed secret key after

**Comment by gayanov** [comment]
I am refresh page on F5 every:
https://vimeo.com/user105064687/review/372448075/631ae412b5
after 5-6 attemps i get 404 (this result ok)

**Comment by C0nw0nk** [comment]
Looking at your changes to the script i think it is your `nginx.conf` file please share your nginx configuration.

Also enable eror logs and look at the nginx `error.log` file inside `/logs/`

**Comment by gayanov** [comment]
nginx config: https://pastebin.com/kW3eavkJ
error_log: https://pastebin.com/NubLY7Ce

**Comment by C0nw0nk** [comment]
Your issue is this.

ndk.set_var: directive "set_encode_hex" not found or does not use ndk_set_var_value

I will update the script for clients who do not support this.

In the mean time change this config value to fix it.
`local encrypt_javascript_output = 0`

to

`local encrypt_javascript_output = 1`

That will disable javascript encryption.

**Comment by gayanov** [comment]
this change encrypt_javascript_output value 0 to 1 is vulnerable?

**Comment by gayanov** [comment]
it works! Thanks, i see source page, get not encoded script by eval(), ohh, okey, waiting for release from you)

**Comment by C0nw0nk** [comment]
vulnerable? no.

It is just a bug with Nginx builds that do not support that function i will make a fix when i have time :)

**Comment by C0nw0nk** [comment]
@gayanov 

`local encrypt_javascript_output = 2`

or

`local encrypt_javascript_output = 4`

Try either  of those if you want eencryption still should work.

It is just my hex encryption method that i need to fix it looks like.

**Comment by gayanov** [comment]
can you say good version nginx version with you lua?

**Comment by C0nw0nk** [comment]
Updated and fixed.

https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/4e5060ef4120c8d01e6f117789755e890b49d3b5

As can be read here.
ngx_devel_kit

https://github.com/openresty/lua-nginx-module
https://github.com/simplresty/ngx_devel_kit/tags

That was a Lua dependancy now it is not :) and this script can now function without it.
