### ISSUE TITLE
Md5 encryption

### ISSUE THREAD

**Issue by gayanov** [C0nw0nk/Nginx-Lua-Anti-DDoS#7]
Will the md5 encryption method be replaced by sha256?
Since the sha256 method considers it more reliable.
![screen](https://sun9-56.userapi.com/c857636/v857636743/e0849/uBSASNxV3cA.jpg)

**Comment by C0nw0nk** [comment]
No becausse it already does hmac_sha1 around it. Unless a CVE for people to hack sha1 without the required secret key it is pointless.

the hmac_sha1 requires the secret var in the script as a password what nobody will know but you anyway.
