### ISSUE TITLE
add an activation protection options on a rate limiting

### ISSUE THREAD

**Issue by louishot** [C0nw0nk/Nginx-Lua-Anti-DDoS#9]
I think add Rate limiting options is very nice.

For example
a standard Rate limiting 100 requests per second, if over that set that user ip address rate limiting to a low value E.g. 50 requests per second with a time period. like 3600 seconds,  if that user still hit this low value rate limiting then active the protection. (a global statistics or a solo vhost) if don't have hit the low value of rate limiting will expired after period seconds in ngx.shared.DICT.
requests more than X times in X second then ban ip in ngx.shared.DICT (403)
requests more than X times in X second then ban ip use ipset & iptables. (Network layer blocking).

In addition, better control should be divided into:
trigger
action

E.g
trigger: 100q/1s/ip
action: low-value-rate-limiting-50qps
period: 3600s

trigger: ip is low-value-rate-limiting and 50q/s
action: protection
period: 3600s

trigger: 10000q/3600s/ip
action: deny
period: 300s

trigger: 15000q/7200s/ip
action: deny-ipset
period: 1800s

trigger: 10q/1s/ip and uri=/api/*
action: api-delay
period: 30

trigger: 20q/1s/ip and uri=/api/*
action: api-low-value-rate-limiting-5qps
period: 3600

trigger: ip is api-low-value-rate-limiting-5qps and 5q/s
action: deny
period: 1800s

trigger: x..
action: x...
period: x....

trigger: x..
action: x...
period: x....

trigger: 20000q/86400s/ip
action: deny-ipset
period: 86400s

This looks more like waf

**Comment by C0nw0nk** [comment]
I am not going  to build un-needed / unnecessary features into this script that Nginx already has under its hood and can already do. You are welcome to fork my project and build it in yourself.

You should use what Nginx gives you for a rate limiting protection.
http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html
http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

**Comment by louishot** [comment]
> I am not going to build un-needed / unnecessary features into this script that Nginx already has under its hood and can already do. You are welcome to fork my project and build it in yourself.
> 
> You should use what Nginx gives you for a rate limiting protection.
> http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html
> http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

This will dynamically activate protection based on the rate. not always on. ya I think will make a new one

I see ngx_http_limit_req and ngx_http_limit_conn but we still have lua-resty-limit-traffic

**Comment by AndreiG6** [comment]
Drop a link to your fork here when you get it working, I think that it'd be
a useful feature to have as well
